apiVersion: batch/v1
kind: Job
metadata:
  name: a3-prime-job
spec:
  template:
    spec:
      containers:
      - name: primes-in-range-1
        image: docker.io/library/a3_prime_nums:1.0
        imagePullPolicy: Never
        command: ["python", "a3.py", "1", "33333"]
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "1"
            memory: "512Mi"
      - name: primes-in-range-2
        image: docker.io/library/a3_prime_nums:1.0
        imagePullPolicy: Never
        command: ["python", "a3.py", "33334", "66666"]
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "1"
            memory: "512Mi"
      - name: primes-in-range-3
        image: docker.io/library/a3_prime_nums:1.0
        imagePullPolicy: Never
        command: ["python", "a3.py", "66667", "99999"]
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "1"
            memory: "512Mi"
      restartPolicy: Never
